# PyTorch 1.0 Tensor Basic Usage

- Create Tensor
- Indexing,Joining,Slicing
- Initialization
- Math Operations

## 1. Create Tensor
### 1) random numbers

In [2]:
import torch

# torch.rand(sizes) -> [0,1)
x = torch.rand(2,3)
x

tensor([[0.8325, 0.1116, 0.7644],
        [0.5820, 0.1500, 0.1052]])

In [3]:
# torch.randn(sizes) -> Z(0,1)
x = torch.randn(2,3)
x

tensor([[-1.2252,  0.6483, -1.2252],
        [-0.6156,  1.3840, -1.2349]])

In [4]:
# torch.randperm(n) -> permutation of 0~n
x = torch.randperm(5)
x

tensor([4, 0, 2, 3, 1])

### 2) zeros, ones, arange

In [5]:
# torch.zeros(2,3) -> [[0,0,0],[0,0,0]]
x = torch.zeros(2,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# torch.ones(2,3) -> [[0,0,0],[0,0,0]]
x = torch.ones(2,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# torch.arange(start,end,step=1) -> [start,end) with step
x = torch.arange(0,3,step=0.5)
x

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])

### 3) Tensor Data Type

In [7]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor(2,3)
x

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.2981e+21, 6.3828e+28]])

In [8]:
# torch.FloatTensor(size or list)
x = torch.FloatTensor([2,3])
x

tensor([2., 3.])

In [9]:
# tensor.type_as(tensor_type)
x = x.type_as(torch.IntTensor())
x

tensor([2, 3], dtype=torch.int32)

### 4) Numpy to Tensor, Tensor to Numpy

In [10]:
import numpy as np

# torch.from_numpy(ndarray) -> tensor

x1 = np.ndarray(shape=(2,3), dtype=int,buffer=np.array([1,2,3,4,5,6]))
x2 = torch.from_numpy(x1)

x2

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# tensor.numpy() -> ndarray
x3 = x2.numpy()
x3

array([[1, 2, 3],
       [4, 5, 6]])

### 5) Tensor on CPU & GPU

In [12]:
x = torch.FloatTensor([[1,2,3],[4,5,6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
#x_gpu = x.cuda()
#x_gpu

In [14]:
#x_cpu = x_gpu.cpu()
#x_cpu

### 6) Tensor Size

In [13]:
# tensor.size() -> indexing also possible

x = torch.FloatTensor(10,12,3,3)
x.size()[:]

torch.Size([10, 12, 3, 3])

## 2. Indexing, Slicing, Joining
### 1) Indexing

In [14]:
# torch.index_select(input, dim, index)

x = torch.rand(4,3)
out = torch.index_select(x,0,torch.LongTensor([0,3]))

print(x)
print(out)

tensor([[0.9823, 0.3204, 0.0317],
        [0.7458, 0.7507, 0.0735],
        [0.8803, 0.5497, 0.3491],
        [0.8727, 0.2006, 0.5053]])
tensor([[0.9823, 0.3204, 0.0317],
        [0.8727, 0.2006, 0.5053]])


In [15]:
# pythonic indexing also works

print(x[:,0])
print(x[0,:])
print(x[0:2,0:2])

tensor([0.9823, 0.7458, 0.8803, 0.8727])
tensor([0.9823, 0.3204, 0.0317])
tensor([[0.9823, 0.3204],
        [0.7458, 0.7507]])


In [16]:
# torch.masked_select(input, mask)

x = torch.randn(2,3)
mask = torch.ByteTensor([[0,0,1],[0,1,0]])
out = torch.masked_select(x,mask)

print(x)
print(mask)
print(out)

tensor([[-0.1523,  0.4779, -0.1363],
        [ 0.6743,  0.0978,  0.8855]])
tensor([[0, 0, 1],
        [0, 1, 0]], dtype=torch.uint8)
tensor([-0.1363,  0.0978])


### 2) Joining

In [17]:
# torch.cat(seq, dim=0) -> concatenate tensor along dim

x = torch.FloatTensor([[1,2,3],[4,5,6]])
y = torch.FloatTensor([[-1,-2,-3],[-4,-5,-6]])
z1 = torch.cat([x,y],dim=0)
z2 = torch.cat([x,y],dim=1)

print(x)
print(y)
print(z1)
print(z2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.,  2.,  3., -1., -2., -3.],
        [ 4.,  5.,  6., -4., -5., -6.]])


In [18]:
# torch.stack(sequence,dim=0) -> stack along new dim

x = torch.FloatTensor([[1,2,3],[4,5,6]])
x_stack = torch.stack([x,x,x,x],dim=0)

x_stack

tensor([[[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]],

        [[1., 2., 3.],
         [4., 5., 6.]]])

### 3) Slicing

In [19]:
# torch.chunk(tensor, chunks, dim=0) -> tensor into num chunks

x_1, x_2 = torch.chunk(z1,2,dim=0)
y_1, y_2, y_3 = torch.chunk(z1,3,dim=1)

print(z1)
print(x_1)
print(x_2)
print(z1)
print(y_1)
print(y_2)
print(y_3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.],
        [ 4.],
        [-1.],
        [-4.]])
tensor([[ 2.],
        [ 5.],
        [-2.],
        [-5.]])
tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]])


In [20]:
# torch.split(tensor,split_size,dim=0) -> split into specific size

x1,x2 = torch.split(z1,2,dim=0)
y1 = torch.split(z1,2,dim=1) 

print(z1)
print(x1)
print(x2)
print(y1)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[-1., -2., -3.],
        [-4., -5., -6.]])
(tensor([[ 1.,  2.],
        [ 4.,  5.],
        [-1., -2.],
        [-4., -5.]]), tensor([[ 3.],
        [ 6.],
        [-3.],
        [-6.]]))


### 4) squeezing

In [21]:
# torch.squeeze(input,dim=None) -> reduce dim by 1

x1 = torch.FloatTensor(10,1,3,1,4)
x2 = torch.squeeze(x1)

x1.size(),x2.size()

(torch.Size([10, 1, 3, 1, 4]), torch.Size([10, 3, 4]))

In [24]:
# torch.unsqueeze(input,dim=None) -> add dim by 1

x1 = torch.FloatTensor(10,3,4)
x2 = torch.unsqueeze(x1,dim=0)

x1.size(),x2.size()

(torch.Size([10, 3, 4]), torch.Size([1, 10, 3, 4]))

## 3. Initialization

In [25]:
#import torch.nn.init as init

#x1 = init.uniform(torch.FloatTensor(3,4),a=0,b=9) 
#x2 = init.normal(torch.FloatTensor(3,4),std=0.2)
#x3 = init.constant(torch.FloatTensor(3,4),3.1415)

#x1,x2,x3
#sum(x2)

## 4. Math Operations
### 1) Arithmetic operations

In [26]:
# torch.add()

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
add = torch.add(x1,x2)

x1,x2,add,x1+x2,x1-x2

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.]]), tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [27]:
# torch.add() broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.add(x1,10)

x1,x2,x1+10,x2-10

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), tensor([[11., 12., 13.],
         [14., 15., 16.]]), tensor([[11., 12., 13.],
         [14., 15., 16.]]), tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [28]:
# torch.mul() -> size better match

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.mul(x1,x2)

print(x3)
print(x1*x2)
print(x1.size(), x3.size())

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
torch.Size([2, 3]) torch.Size([2, 3])


In [29]:
# torch.mul() -> broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = x1*10

x2

tensor([[10., 20., 30.],
        [40., 50., 60.]])

In [30]:
# torch.div() -> size better match

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])
x2 = torch.FloatTensor([[1,2,3],[4,5,6]])
x3 = torch.div(x1,x2)

x3

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [31]:
# torch.div() -> broadcasting

x1 = torch.FloatTensor([[1,2,3],[4,5,6]])

x1/5

tensor([[0.2000, 0.4000, 0.6000],
        [0.8000, 1.0000, 1.2000]])

### 2) Other Math Operations

In [32]:
# torch.pow(input,exponent)

x1 = torch.rand(3,4)
print(x1)
print(torch.pow(x1,2))
print(x1**2)

tensor([[0.3336, 0.6467, 0.7652, 0.2567],
        [0.0880, 0.1854, 0.6921, 0.1325],
        [0.8744, 0.2403, 0.1648, 0.6326]])
tensor([[0.1113, 0.4182, 0.5856, 0.0659],
        [0.0077, 0.0344, 0.4790, 0.0175],
        [0.7645, 0.0577, 0.0272, 0.4002]])
tensor([[0.1113, 0.4182, 0.5856, 0.0659],
        [0.0077, 0.0344, 0.4790, 0.0175],
        [0.7645, 0.0577, 0.0272, 0.4002]])


In [33]:
# torch.exp(tensor,out=None) 

x1 = torch.rand(3,4)
print(x1)
print(torch.exp(x1))

tensor([[0.4511, 0.7183, 0.6387, 0.1931],
        [0.4809, 0.5399, 0.6277, 0.8499],
        [0.7566, 0.7345, 0.0896, 0.3387]])
tensor([[1.5700, 2.0509, 1.8939, 1.2131],
        [1.6175, 1.7159, 1.8733, 2.3394],
        [2.1311, 2.0844, 1.0937, 1.4031]])


In [34]:
# torch.log(input, out=None) -> natural logarithm

x1 = torch.rand(3,4)
print(x1)
print(torch.log(x1))

tensor([[0.8547, 0.2776, 0.1730, 0.6723],
        [0.6678, 0.1130, 0.8238, 0.8398],
        [0.8041, 0.3210, 0.5065, 0.4572]])
tensor([[-0.1570, -1.2815, -1.7547, -0.3970],
        [-0.4038, -2.1803, -0.1938, -0.1746],
        [-0.2181, -1.1363, -0.6802, -0.7827]])


### 3) Matrix operations

In [35]:
# torch.mm(mat1, mat2) -> matrix multiplication

x1 = torch.randint(0,3,(3,4)) 
x2 = torch.randint(0,3,(4,5))

print(x1)
print(x2)
print(torch.mm(x1,x2))

tensor([[1, 2, 1, 0],
        [1, 0, 1, 0],
        [0, 2, 2, 1]])
tensor([[2, 2, 1, 1, 2],
        [1, 1, 1, 0, 2],
        [2, 2, 1, 0, 0],
        [1, 0, 0, 0, 0]])
tensor([[6, 6, 4, 1, 6],
        [4, 4, 2, 1, 2],
        [7, 6, 4, 0, 4]])


In [36]:
# torch.bmm(batch1, batch2) -> batch matrix multiplication

x1 = torch.FloatTensor(10,3,4)
x2 = torch.FloatTensor(10,4,5)

torch.bmm(x1,x2).size()

torch.Size([10, 3, 5])

In [37]:
# torch.dot(tensor1,tensor2) -> dot product of two tensor

x1 = torch.tensor([2, 3])
x2 = torch.tensor([2, 1])
print(x1)
print(x2)
print(torch.dot(x1, x2))


tensor([2, 3])
tensor([2, 1])
tensor(7)


In [38]:
# torch.t(matrix) -> transposed matrix

x1 = torch.randint(0,3,(3,4))

x1,x1.t()

(tensor([[1, 2, 2, 0],
         [2, 0, 1, 2],
         [0, 0, 1, 1]]), tensor([[1, 2, 0],
         [2, 0, 0],
         [2, 1, 1],
         [0, 2, 1]]))

In [39]:
# torch.transpose(input,dim0,dim1) -> transposed matrix

x1 = torch.randint(0,3,(10,3,4)) 

x1.size(), torch.transpose(x1,1,2).size(), x1.transpose(1,2).size()

(torch.Size([10, 3, 4]), torch.Size([10, 4, 3]), torch.Size([10, 4, 3]))

In [40]:
# torch.eig(a,eigenvectors=False) -> eigen_value, eigen_vector

x1 = torch.FloatTensor(4,4)

x1,torch.eig(x1,True)

(tensor([[ 0.0000e+00, -4.6566e-10, -1.8121e-19,  1.5849e+29],
         [ 2.9463e+29,  1.4607e-19,  3.6423e-06,  2.0699e-19],
         [ 8.6370e-10,  1.8037e+28,  1.2986e+19,  1.7237e+25],
         [ 3.7830e-39,  4.5559e-41, -1.7634e-19,  3.7021e-40]]),
 (tensor([[ 1.2986e+19,  0.0000e+00],
          [-1.1272e+16,  1.9501e+16],
          [-1.1272e+16, -1.9501e+16],
          [ 2.2544e+16,  0.0000e+00]]),
  tensor([[-1.6574e-28,  2.7496e-23, -4.7734e-23,  5.4991e-23],
          [-3.7604e-18, -7.2056e-10,  1.0812e-12,  7.1869e-10],
          [ 1.0000e+00,  1.0000e+00,  0.0000e+00, -1.0000e+00],
          [-1.3579e-38,  3.9177e-36,  6.7779e-36,  7.8219e-36]])))